name: hello world
run-name: ${{ github.actor }} greeting
on: [push]
jobs:
   greet:
      runs-on: ubuntu-latest
      steps:
         - uses: action/checkout@v3
         - uses: actions/setup-node@v3
           with:
              node-version: "14"
         - run: hello world!
